name: quic
description: QUIC protocol implementation written in pure Dart
version: 1.0.0
repository: https://github.com/perbone/quic

environment:
  sdk: ^3.4.1

#dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
